### PR TITLE
anemone_mempool: Use malloc instead of memalign

### PR DESCRIPTION
**Pull request by erikd-ambiata**
OSX does not have `memalign`.

! @amosr @jystic @tranma 
/jury approved @amosr @jystic

### CODE REVIEW

**Comment by amosr** [comment]
Ah, can you remove the include of <malloc.h> while you're there?

**Comment by erikd-ambiata** [comment]
Done!

**Comment by amosr** [comment]
👍

**Comment by jystic** [comment]
✌️

**Comment by erikd-ambiata** [comment]
I suppose I need to follow this in Zebra as well.

**Pull request merged**
